#ifndef CLASSICAL_RNG_INTERNAL_CONSTANTS_H
#define CLASSICAL_RNG_INTERNAL_CONSTANTS_H

#include <stdint.h>

/* Namespaced descendants of the mathematical constants used by version 1. */
#define CRNG_CONSTANT_PHI   UINT64_C(0x9e3779b97f4a7c15)
#define CRNG_CONSTANT_E     UINT64_C(0xbf58476d1ce4e5b9)
#define CRNG_CONSTANT_PI    UINT64_C(0x94d049bb133111eb)
#define CRNG_CONSTANT_ROOT2 UINT64_C(0x6a09e667f3bcc909)

#define CRNG_V1_DEFAULT_SEED \
    (CRNG_CONSTANT_PHI ^ CRNG_CONSTANT_E ^ CRNG_CONSTANT_PI ^ CRNG_CONSTANT_ROOT2)

#endif /* CLASSICAL_RNG_INTERNAL_CONSTANTS_H */
